analyze_shelve:
  description: >
    Use the Vision Tool to collect visual data and caption the current product arrangement.
    Conduct a thorough analysis of shelve {shelve} in the store.
    Prepare a detailed report highlighting the current layout, products, product placement, and any observed issues.
    Ensure the report is detailed at the level of product names.
  expected_output: >
    A comprehensive report on shelve {shelve}, including visual data,
    analysis of product placement, space utilization, and any recommendations for improvement.
  agent: space_planner

provide_recommendations:
  description: >
    Review the report on shelve {shelve} provided by the Space Planner.
    Utilize your immense knowledge of the retail market and internet to assess current trends relevant to the products in this shelve ({shelve}).
    Develop expert recommendations to optimize sales and customer satisfaction.
    Ensure the recommendations are detailed and includes details like product names.
  expected_output: >
    A set of actionable recommendations for rearranging the {shelve} shelve,
    aligned with current market trends and consumer preferences.
  agent: market_analyst

create_action_plan:
  description: >
    List the recommendations from the Market Analyst, 
    Then develop a detailed action plan
    for Store manager and Store buyer to implement the changes.
    Ensure the plan includes the market analyst recommendations.
    Ensure the plan is practical and outlines the steps needed to rearrange the products effectively.
    Be smart and well explained.
    Give the explanation of your recomendations and the goal to achieve.
  expected_output: >
    A detailed list of recomendation and action plan for rearranging and improving the {shelve} shelve according to market trends,
    including market analyst recomendations and translation into practical tasks for the Store manager and the Buyer.
  agent: space_planner